on:
  pull_request:
    branches:
    - "hotfix*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "develop"                     # If blank, default: triggered branch
        destination_branch: "master"          # If blank, default: master
        github_token: ${{ secrets.GITHUB_TOKEN }}